# Generated by Django 5.0.3 on 2024-03-13 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_confirmed',
        ),
    ]
