# Generated by Django 5.0.3 on 2024-03-06 14:34

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_description'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('custom_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
